jobs:
  test:
    runs-on: ubuntu-latest
env:
  APP_NAME: my-app
jobs:
  build:
   runs-on: ubuntu-latest
   env:
     NODE_ENV: production
   steps:
     - name: show them
       env:
        GREETING: hello
      runs: echo "$APP_NAME $NODE_ENV $GREETING"  
